'use client';

import { useState, useTransition, useRef } from 'react';
import Link from 'next/link';
import { applyToDemand } from '@/lib/actions/applications';

async function generateCvPdf(data: {
  name: string; email: string; phone: string; skills: string[];
}): Promise<File | null> {
  try {
    const { pdf, Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer');

    const s = StyleSheet.create({
      page:         { fontFamily: 'Helvetica', fontSize: 10, padding: 48, color: '#1A1A1A', lineHeight: 1.5 },
      accentBar:    { height: 4, backgroundColor: '#007AFF', marginBottom: 28 },
      name:         { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
      contact:      { fontSize: 10, color: '#636366', marginBottom: 20 },
      divider:      { borderBottomWidth: 0.5, borderBottomColor: '#E5E5EA', marginBottom: 16 },
      sectionTitle: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#007AFF', letterSpacing: 0.6, marginBottom: 8, textTransform: 'uppercase' },
      tagRow:       { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginBottom: 10 },
      tag:          { backgroundColor: '#EBF3FF', color: '#007AFF', fontSize: 9, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 4 },
      footer:       { position: 'absolute', bottom: 32, left: 48, right: 48, fontSize: 8, color: '#C7C7CC', textAlign: 'center' },
    });

    const contactLine = [data.email, data.phone].filter(Boolean).join(' · ');
    const doc = (
      <Document title={`${data.name} – CV`}>
        <Page size="A4" style={s.page}>
          <View style={s.accentBar} />
          <Text style={s.name}>{data.name}</Text>
          {contactLine ? <Text style={s.contact}>{contactLine}</Text> : <View />}
          {data.skills.length > 0 && (
            <View>
              <View style={s.divider} />
              <Text style={s.sectionTitle}>Skills</Text>
              <View style={s.tagRow}>
                {data.skills.map((sk, i) => <Text key={i} style={s.tag}>{sk}</Text>)}
              </View>
            </View>
          )}
          <Text style={s.footer}>
            {`Generated by WorkforceX · ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`}
          </Text>
        </Page>
      </Document>
    );

    const blob = await pdf(doc).toBlob();
    const safeName = data.name.replace(/[^a-z0-9]/gi, '-').toLowerCase();
    return new File([blob], `${safeName}-cv.pdf`, { type: 'application/pdf' });
  } catch {
    return null;
  }
}

async function generateTestData(demandId: string, demandTitle: string) {
  const res = await fetch('/api/generate-test-data', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      path: `/careers/${demandId}/apply`,
      fields: [
        { name: 'name', type: 'text', label: 'Full Name', placeholder: 'Maria Schmidt' },
        { name: 'email', type: 'email', label: 'Email Address' },
        { name: 'phone', type: 'tel', label: 'Phone', placeholder: '+49 170 1234567' },
        { name: 'desired_rate', type: 'number', label: 'Desired Rate / Salary' },
        { name: 'skills', type: 'tags', label: 'Skills', placeholder: 'React, TypeScript, Node.js' },
        { name: 'cover_letter', type: 'textarea', label: 'Cover Letter', placeholder: `I am applying for the ${demandTitle} position because…` },
      ],
      pageContext: `Position: ${demandTitle}`,
    }),
  });
  if (!res.ok) return null;
  return res.json() as Promise<Record<string, string>>;
}

type Step = 'details' | 'account' | 'application' | 'success';

const STEP_LABELS: Record<Step, string> = {
  details:     'About you',
  account:     'Create account',
  application: 'Application',
  success:     'Done',
};
const STEPS: Step[] = ['details', 'account', 'application', 'success'];

interface Props {
  demandId: string;
  demandTitle: string;
  contractType: string;
}

const RATE_META: Record<string, { label: string; hint: string; types: { value: string; label: string }[] }> = {
  permanent:  { label: 'Wunschgehalt (brutto)',  hint: 'Monatliches Bruttogehalt', types: [{ value: 'monthly', label: '/Monat' }] },
  internship: { label: 'Vergütungserwartung',    hint: 'Monatliche Vergütung', types: [{ value: 'monthly', label: '/Monat' }] },
  freelance:  { label: 'Wunschsatz',             hint: 'Gewünschte Rate', types: [{ value: 'daily', label: '/Tag' }, { value: 'hourly', label: '/Std.' }] },
  contractor: { label: 'Wunschsatz',             hint: 'Gewünschte Rate', types: [{ value: 'daily', label: '/Tag' }, { value: 'hourly', label: '/Std.' }] },
};

function StepIndicator({ current }: { current: Step }) {
  const activeSteps = STEPS.slice(0, -1);
  const currentIdx = activeSteps.indexOf(current);
  return (
    <div className="flex items-center gap-2">
      {activeSteps.map((s, i) => (
        <div key={s} className="flex items-center gap-2">
          <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[11px] font-bold transition-all ${
            i < currentIdx ? 'bg-[#34C759] text-white' :
            i === currentIdx ? 'bg-[#007AFF] text-white' :
            'bg-[#E5E5EA] text-[#8E8E93]'
          }`}>
            {i < currentIdx ? '✓' : i + 1}
          </div>
          <span className={`text-[12px] font-medium ${i === currentIdx ? 'text-black' : 'text-[#8E8E93]'}`}>
            {STEP_LABELS[s]}
          </span>
          {i < activeSteps.length - 1 && <div className="w-5 h-px bg-[#E5E5EA] mx-0.5" />}
        </div>
      ))}
    </div>
  );
}

function Field({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) {
  return (
    <div>
      <label className="block text-[13px] font-medium text-[#3C3C43] mb-1.5">{label}</label>
      {children}
      {hint && <p className="text-[11px] text-[#8E8E93] mt-1">{hint}</p>}
    </div>
  );
}

const inputCls = "w-full h-11 px-4 rounded-[10px] border border-[#E5E5EA] bg-white text-[15px] placeholder-[#C7C7CC] focus:outline-none focus:border-[#007AFF] focus:ring-2 focus:ring-[#007AFF]/20 transition-all";

function SkillsInput({ skills, onChange }: { skills: string[]; onChange: (s: string[]) => void }) {
  const [input, setInput] = useState('');

  function addSkill(raw: string) {
    const parts = raw.split(/[,;]+/).map(s => s.trim()).filter(Boolean);
    if (!parts.length) return;
    const merged = [...skills, ...parts];
    onChange(merged.filter((s, i) => merged.indexOf(s) === i));
    setInput('');
  }

  function handleKey(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      addSkill(input);
    } else if (e.key === 'Backspace' && !input && skills.length) {
      onChange(skills.slice(0, -1));
    }
  }

  function removeSkill(s: string) {
    onChange(skills.filter(x => x !== s));
  }

  return (
    <div
      className="min-h-[44px] px-3 py-2 rounded-[10px] border border-[#E5E5EA] bg-white focus-within:border-[#007AFF] focus-within:ring-2 focus-within:ring-[#007AFF]/20 transition-all flex flex-wrap gap-1.5 cursor-text"
      onClick={() => document.getElementById('skills-input')?.focus()}
    >
      {skills.map(s => (
        <span key={s} className="flex items-center gap-1 bg-[#007AFF]/10 text-[#007AFF] text-[13px] font-medium px-2.5 py-0.5 rounded-full">
          {s}
          <button type="button" onClick={() => removeSkill(s)} className="text-[#007AFF]/60 hover:text-[#007AFF] ml-0.5 leading-none">×</button>
        </span>
      ))}
      <input
        id="skills-input"
        type="text"
        value={input}
        onChange={e => setInput(e.target.value)}
        onKeyDown={handleKey}
        onBlur={() => { if (input.trim()) addSkill(input); }}
        placeholder={skills.length === 0 ? 'React, TypeScript… (Enter or comma to add)' : ''}
        className="flex-1 min-w-[120px] outline-none text-[14px] bg-transparent placeholder-[#C7C7CC]"
      />
    </div>
  );
}

export function ApplyForm({ demandId, demandTitle, contractType }: Props) {
  const [step, setStep] = useState<Step>('details');
  const [error, setError] = useState('');
  const [isPending, startTransition] = useTransition();
  const [isFilling, setIsFilling] = useState(false);
  const cvRef = useRef<HTMLInputElement>(null);
  const [generatedCvFile, setGeneratedCvFile] = useState<File | null>(null);
  const [cvFileName, setCvFileName] = useState<string | null>(null);

  const rateMeta = RATE_META[contractType] ?? RATE_META.contractor;

  const [form, setForm] = useState({
    name: '', email: '', phone: '',
    desiredRate: '',
    desiredRateType: contractType === 'permanent' || contractType === 'internship' ? 'monthly' : 'daily',
    skills: [] as string[],
    password: '', confirmPassword: '',
    coverLetter: '',
  });

  function update<K extends keyof typeof form>(field: K, value: typeof form[K]) {
    setForm(prev => ({ ...prev, [field]: value }));
    setError('');
  }

  async function fillAI() {
    setIsFilling(true);
    try {
      const data = await generateTestData(demandId, demandTitle);
      if (data) {
        const skillsArr = data.skills
          ? data.skills.split(/[,;]+/).map((s: string) => s.trim()).filter(Boolean)
          : [];
        const nextForm = {
          name:            data.name         || form.name,
          email:           data.email        || form.email,
          phone:           data.phone        || form.phone,
          desiredRate:     data.desired_rate || form.desiredRate,
          desiredRateType: form.desiredRateType,
          skills:          skillsArr.length  ? skillsArr : form.skills,
          password:        'Test1234!',
          confirmPassword: 'Test1234!',
          coverLetter:     data.cover_letter || form.coverLetter,
        };
        setForm(nextForm);

        // Auto-generate a CV PDF from the AI-filled data
        const cvFile = await generateCvPdf({
          name: nextForm.name,
          email: nextForm.email,
          phone: nextForm.phone,
          skills: nextForm.skills,
        });
        if (cvFile) {
          setGeneratedCvFile(cvFile);
          setCvFileName(cvFile.name);
        }
      }
    } finally {
      setIsFilling(false);
    }
  }

  function nextFromDetails() {
    if (!form.name.trim() || !form.email.trim()) { setError('Name and email are required.'); return; }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) { setError('Please enter a valid email address.'); return; }
    setStep('account');
  }

  function nextFromAccount() {
    if (!form.password) { setError('Please set a password.'); return; }
    if (form.password.length < 8) { setError('Password must be at least 8 characters.'); return; }
    if (form.password !== form.confirmPassword) { setError('Passwords do not match.'); return; }
    setStep('application');
  }

  function submit() {
    startTransition(async () => {
      const fd = new FormData();
      fd.append('demand_id', demandId);
      fd.append('name', form.name);
      fd.append('email', form.email);
      fd.append('phone', form.phone);
      fd.append('password', form.password);
      fd.append('cover_letter', form.coverLetter);
      fd.append('skills', form.skills.join(','));
      if (form.desiredRate) {
        fd.append('desired_rate', form.desiredRate);
        fd.append('desired_rate_type', form.desiredRateType);
      }
      const cvFile = cvRef.current?.files?.[0] ?? generatedCvFile ?? undefined;
      if (cvFile) fd.append('cv_file', cvFile);

      const result = await applyToDemand(fd);
      if (result.emailExists) { setError('An account with this email already exists. Please sign in to apply.'); setStep('account'); return; }
      if (result.error) { setError(result.error); return; }
      setStep('success');
    });
  }

  if (step === 'success') {
    return (
      <div className="text-center py-8">
        <div className="w-16 h-16 rounded-full bg-[#34C759]/10 flex items-center justify-center mx-auto mb-4">
          <svg className="w-8 h-8 text-[#34C759]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        </div>
        <h2 className="text-[24px] font-bold text-black mb-2">Application submitted!</h2>
        <p className="text-[15px] text-[#8E8E93] mb-1">
          Your application for <strong className="text-black">{demandTitle}</strong> has been received.
        </p>
        <p className="text-[14px] text-[#8E8E93] mb-6">
          We created your account — sign in to complete your profile and track your application.
        </p>
        <Link href="/login" className="inline-block px-8 py-3.5 rounded-2xl text-white text-[15px] font-semibold" style={{ backgroundColor: '#007AFF' }}>
          Sign in to your account →
        </Link>
        <p className="mt-4">
          <Link href="/careers" className="text-[13px] text-[#8E8E93] hover:text-[#007AFF]">Browse more positions</Link>
        </p>
      </div>
    );
  }

  return (
    <div>
      {/* Header row: step indicator + AI fill */}
      <div className="flex items-center justify-between mb-6">
        <StepIndicator current={step} />
        <button
          type="button"
          onClick={fillAI}
          disabled={isFilling}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-[12px] font-semibold text-[#007AFF] bg-[#007AFF]/8 hover:bg-[#007AFF]/15 transition-colors disabled:opacity-50 disabled:cursor-wait flex-shrink-0"
        >
          {isFilling ? (
            <svg className="w-3.5 h-3.5 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5}><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" /></svg>
          ) : (
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d="M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 17l-6.2 4.3 2.4-7.4L2 9.4h7.6z" /></svg>
          )}
          {isFilling ? 'Generating…' : 'Fill with AI'}
        </button>
      </div>

      {/* Step 1: About you */}
      {step === 'details' && (
        <div className="space-y-4">
          <Field label="Full Name *">
            <input type="text" value={form.name} onChange={e => update('name', e.target.value)} placeholder="Maria Schmidt" autoFocus className={inputCls} />
          </Field>
          <Field label="Email Address *">
            <input type="email" value={form.email} onChange={e => update('email', e.target.value)} placeholder="maria@example.com" className={inputCls} />
          </Field>
          <Field label="Phone" hint="Optional — helps us reach you faster">
            <input type="tel" value={form.phone} onChange={e => update('phone', e.target.value)} placeholder="+49 170 1234567" className={inputCls} />
          </Field>
          {/* Desired rate */}
          <Field label={rateMeta.label} hint={`${rateMeta.hint} · Optional`}>
            <div className="flex gap-2">
              <input
                type="number"
                min="0"
                value={form.desiredRate}
                onChange={e => update('desiredRate', e.target.value)}
                placeholder="0"
                className={inputCls + ' flex-1'}
              />
              {rateMeta.types.length > 1 ? (
                <select
                  value={form.desiredRateType}
                  onChange={e => update('desiredRateType', e.target.value)}
                  className="h-11 px-3 rounded-[10px] border border-[#E5E5EA] bg-white text-[14px] text-[#3C3C43] focus:outline-none focus:border-[#007AFF] focus:ring-2 focus:ring-[#007AFF]/20 transition-all"
                >
                  {rateMeta.types.map(rt => <option key={rt.value} value={rt.value}>{rt.label}</option>)}
                </select>
              ) : (
                <div className="h-11 px-4 flex items-center rounded-[10px] bg-[#F2F2F7] text-[14px] text-[#8E8E93] whitespace-nowrap">
                  {rateMeta.types[0].label}
                </div>
              )}
            </div>
          </Field>
          {/* Skills */}
          <Field label="Skills" hint="Enter your key skills — press Enter or comma to add">
            <SkillsInput skills={form.skills} onChange={v => update('skills', v)} />
          </Field>
          {error && <p className="text-[13px] text-[#FF3B30]">{error}</p>}
          <button onClick={nextFromDetails} className="w-full h-12 rounded-2xl text-white text-[16px] font-semibold transition-opacity hover:opacity-90" style={{ backgroundColor: '#007AFF' }}>
            Continue →
          </button>
        </div>
      )}

      {/* Step 2: Account */}
      {step === 'account' && (
        <div className="space-y-4">
          <div className="bg-[#F9F9FB] rounded-2xl px-4 py-3 text-[13px] text-[#3C3C43] mb-2">
            Creating account for <strong>{form.email}</strong>
          </div>
          <Field label="Password *" hint="At least 8 characters">
            <input type="password" value={form.password} onChange={e => update('password', e.target.value)} placeholder="••••••••" autoFocus className={inputCls} />
          </Field>
          <Field label="Confirm Password *">
            <input type="password" value={form.confirmPassword} onChange={e => update('confirmPassword', e.target.value)} placeholder="••••••••" className={inputCls} />
          </Field>
          {error && <p className="text-[13px] text-[#FF3B30]">{error}</p>}
          <div className="flex gap-3">
            <button onClick={() => { setStep('details'); setError(''); }} className="flex-1 h-12 rounded-2xl text-[16px] font-semibold border border-[#E5E5EA] text-[#3C3C43] hover:bg-[#F2F2F7] transition-colors">
              ← Back
            </button>
            <button onClick={nextFromAccount} className="flex-1 h-12 rounded-2xl text-white text-[16px] font-semibold transition-opacity hover:opacity-90" style={{ backgroundColor: '#007AFF' }}>
              Continue →
            </button>
          </div>
        </div>
      )}

      {/* Step 3: Application */}
      {step === 'application' && (
        <div className="space-y-4">
          <Field label="Cover Letter" hint="Optional — tell us why you're a great fit">
            <textarea
              value={form.coverLetter}
              onChange={e => update('coverLetter', e.target.value)}
              placeholder={`I am applying for the ${demandTitle} position because…`}
              rows={5}
              autoFocus
              className="w-full px-4 py-3 rounded-[10px] border border-[#E5E5EA] bg-white text-[15px] placeholder-[#C7C7CC] focus:outline-none focus:border-[#007AFF] focus:ring-2 focus:ring-[#007AFF]/20 resize-none transition-all"
            />
          </Field>

          {/* CV Upload */}
          <Field label="CV / Resume" hint="Optional — PDF, max 10 MB">
            <label className={`flex items-center gap-3 px-4 py-3 rounded-[10px] border border-dashed cursor-pointer transition-all group ${cvFileName ? 'border-[#34C759] bg-[#34C759]/4' : 'border-[#C7C7CC] hover:border-[#007AFF] hover:bg-[#007AFF]/4'}`}>
              <div className={`w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 ${cvFileName ? 'bg-[#34C759]/10' : 'bg-[#FF3B30]/10'}`}>
                <svg className={`w-4.5 h-4.5 ${cvFileName ? 'text-[#34C759]' : 'text-[#FF3B30]'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <p className={`text-[14px] font-semibold truncate ${cvFileName ? 'text-[#34C759]' : 'text-black group-hover:text-[#007AFF]'} transition-colors`}>
                    {cvFileName ?? 'Upload CV (PDF)'}
                  </p>
                  {generatedCvFile && !cvRef.current?.files?.[0] && (
                    <span className="text-[10px] font-bold px-1.5 py-0.5 rounded-full bg-[#007AFF] text-white flex-shrink-0">AI</span>
                  )}
                </div>
                <p className="text-[12px] text-[#8E8E93]">{cvFileName ? 'Click to replace' : 'Click to browse'}</p>
              </div>
              <input ref={cvRef} type="file" accept=".pdf,application/pdf" className="sr-only"
                onChange={e => {
                  setError('');
                  const f = e.target.files?.[0];
                  if (f) { setCvFileName(f.name); setGeneratedCvFile(null); }
                }} />
            </label>
          </Field>

          {error && <p className="text-[13px] text-[#FF3B30]">{error}</p>}
          <div className="flex gap-3">
            <button onClick={() => { setStep('account'); setError(''); }} className="flex-1 h-12 rounded-2xl text-[16px] font-semibold border border-[#E5E5EA] text-[#3C3C43] hover:bg-[#F2F2F7] transition-colors">
              ← Back
            </button>
            <button
              onClick={submit}
              disabled={isPending}
              className="flex-1 h-12 rounded-2xl text-white text-[16px] font-semibold transition-opacity hover:opacity-90 disabled:opacity-50"
              style={{ backgroundColor: '#007AFF' }}
            >
              {isPending ? 'Submitting…' : 'Submit Application'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
